### ISSUE TITLE
Model should not be registered during declaration time

### ISSUE THREAD

**Issue by subhashb** [proteanhq/protean#107]
In `core/repository/base.py`, we are currently registering the model class in `BaseModelMeta` upon encountering the declaration via `repo_factory.register(klass)`. This has the side effect that if the test suite uses a different repository for tests, re-registration of a model for an entity fails.

We want models to be initializable explicitly under different conditions, like `DictRepo` for testing, `SQLite` for console/ipython scripts and `Postgresql` for production.

**Comment by subhashb** [comment]
This issue was discovered when writing test cases at the API level.

There are three options to handle this issue:

1. Throw an error on attempting to re-register
1. Write API test cases with the same database that will be used in the production
1. Allow re-registration of Models

Option 3 is dangerous because if the user re-registers a model with a different repository type by accident somewhere in the application, there is no guarantee which repository will finally be in action (Will be decided on import sequence)

Option 1 should probably be implemented, to signal to the user that something is wrong.

Option 2 is the way to go ahead because pragmatically, we should be using stand-in databases at the core application level and actual database in API testing.

**Comment by advishnuprasad** [comment]
@subhashb 
I agree with your points. But on option 2, sometimes we just want to test the business logic. So ideally we would be using pure `DictRepo` to test them. It makes sense to use the same database in test cases if we are testing the queries or DB transactions.

**Comment by subhashb** [comment]
"Business Logic" should never ever be at the API level. If you do see something that is testable in this way, it may be time to refactor. Imagine that at any point in time, you may throw away the API layer and code it anew with some other API framework.

**Comment by subhashb** [comment]
Closed via #111
