### ISSUE TITLE
Establish Repository connections JIT

### ISSUE THREAD

**Issue by subhashb** [proteanhq/protean#113]
RepositoryFactory should prepare adapter objects and establish connections just in time so that connections are kept open only for the necessary duration. Connections are let go after processing the request.

We should initialize a unit of work at the beginning of a request, retrieve repository objects with valid current connections, process the transaction, and commit the unit of work while letting go of active connections.

**Comment by subhashb** [comment]
There are two concerns mixed in the current Adapter class: The act of retrieving and letting of database connections and the database CRUD operations of each entity.

I propose we split existing Adapter class into `Provider` and `Repository`.

`Provider`:
- Initializes Database connectivity from Config file
- Establishes new connections on demand
- Closes connection(s)
- Contextually creates transactions and commits at the end of execution (with the help of a Context Manager?)
- Lookups are associated with the Provider

`Repository`:

- Is the intermediary between `Entity` and Database using the `Model`
- Has support for CRUD operations from entities
- Provides Querying abilities

Typical control flow for a single Entity operation (like one executed in a Python script or an iPython workbook) would be:

1. Initialize Providers
2. Register Model
3. Call operation on Entity (Ex. Account.create)
4. Fetch a fresh Repository object with a live connection 
5. Create a new Transaction
6. Handover operation to Repository (Ex. Repository._create_object)
7. Commit Transaction
8. Return Entity data

Typical control flow for UseCase processing would be:

1. Initialize Providers
2. Register Model(s)
3. Usecase.execute (Ex. CreateAccountUseCase.execute)
4. Create a new Transaction
5. Fetch one or more fresh Repository objects with a live connection 
6. Handover CRUD operations to each Repository (Ex. Repository._create_object)
7. Commit Transaction
8. Return Response

To create and commit transactions, we should use the

**Comment by abhishek-ram** [comment]
Yes this does sound good but in order to implement such a workflow we should have the concept of an application like in celery, flask... this should make things standardized.

**Comment by subhashb** [comment]
Very true. I am trying to keep the framework stateless/application-free - let's see how long we can persist 😄 We will need to go the application route eventually, I guess.
