### ISSUE TITLE
Add support for weak entity

### ISSUE THREAD

**Issue by advishnuprasad** [proteanhq/protean#117]
Right now, all models by default use id field as a primary key.  

Sometimes, we would want to use <entity_id> as a primary key on weak entities. 
For example thumbnails. Thumbnails cannot exist without a file. 
Or
An address. The address doesn't exist without a person/user/customer.

**Comment by subhashb** [comment]
We may have to implement these changes to support Value Objects:

- [ ] Subclass Entity and Value Object from the same parent class
- [ ] Clarify how value objects lifecycle is maintained (There is no lifecycle!)
- [ ] Make Value Objects Immutable
- [ ] Disable `ID` key on Value Objects
- [ ] Disable methods that accept and work with identifiers: `get`, `find_by` etc.
- [ ] Clarify storage and retrieval options for Value Objects
- [ ] Implement equality measures for Entities and Value Objects

**Comment by subhashb** [comment]
Implemented as part of 0.4.x
