### ISSUE TITLE
Enhance BaseEntity Implementation to use the new Field Schema

### ISSUE THREAD

**Issue by subhashb** [proteanhq/protean#12]
Aspects to cover as part of Entity:
- Validations
- Defaults

Notes:
* Rename `BaseEntity` to `Entity`
* Existing Field Definitions can be removed, and field validations can be directly invoked
* Entity can be instantiable via keyword arguments, a dict or a template (Refer to SO question: https://stackoverflow.com/questions/2466191/set-attributes-from-dictionary-in-python)
* Defaults should be set before invoking validate

Add wholesome test cases for Entity Functionality, with tests for all types of fields.

**Comment by abhishek-ram** [comment]
@subhashb if we allow Entity to be declared via template/dict we cannot support instantiation by positional arguments. In my own experience I have use the positional instantiation rather than by template... what do you think?
