### ISSUE TITLE
Add support for limit(number)

### ISSUE THREAD

**Issue by advishnuprasad** [proteanhq/protean#120]
```
Dog.query.filter(name='Jean').filter(owner='John').filter(age=3).limit(1)
```
The above one will apply limit 1 offset on the where query. There are many usecases to make use of `limit`.

**Comment by subhashb** [comment]
Aren't `page` and `per_page` equivalent to `offset` and `limit`?

**Comment by subhashb** [comment]
A related thought. We should probably replace `Pagination` at the Entity level with `ResultSet` and use `Pagination` only when dealing with Use cases and responses?

**Comment by abhishek-ram** [comment]
Yes you are right we need to move Pagination else where as it does not fit here, maybe only used as output for `paginate` method.
`limit` and `offset` sounds better to me and is quite generic.
