### ISSUE TITLE
Make Model Definitions Optional

### ISSUE THREAD

**Issue by subhashb** [proteanhq/protean#121]
- Entities will be registered against a provider, and not models (`default` if not specified)
- The registration process will synthesize a Model from BaseModel directly, in memory
- Meta attributes like `model_name` are derived dynamically during registration
- Optional Models can be used to:
  - Point database column names that are different from attribute names
  - Specifying meta options like `order_by` or `model_name`
  - Any database specific constructs
- A Model’s meta attributes can also be specified directly during registration

**Comment by abhishek-ram** [comment]
Sounds like a good idea
