### ISSUE TITLE
Enrich UseCase with new Entity Model

### ISSUE THREAD

**Issue by subhashb** [proteanhq/protean#20]
As part of the changes:
* Revalidate if `uniquify` should be part of the base UseCase class: It probably is better off in Entity base class, or at least as a separate Decorator that can be used in Create and Update Use cases.
* Handle exceptions (400, 404, 500 etc) centrally in `execute` method
* Move each concrete use case implementation (ShowUseCase, CreateUseCase etc.) into separate files
* Move Tasklet into its own class/file

**Comment by abhishek-ram** [comment]
@subhashb There isn't much code in each use case and so how about moving these concrete implementations to a single module called `generics`?

**Comment by subhashb** [comment]
Yep, ok. 
We can even leave it in the `usecase.py` class that we have now.
