### ISSUE TITLE
Add abstract Field class for storing Entity attributes

### ISSUE THREAD

**Issue by abhishek-ram** [proteanhq/protean#3]
## Purpose
Define a new `Field` class for defining the attribute of an `Entity`. The class will encapsulate the methods for initializing, validating and loading the attribute.

## Implementation
The abstract `Field` class will define a `__init__` method for initializing the field with generic attributes shared by all field types.

1. **default**: If set, this value will be used during entity loading if the field value is missing.
1. **required**: Raise a `ValidationError` if the field value is not supplied during loading.
1. **max_length**: The maximum allowed length for a value of this field.
1. **validators**: Optional list of validators to be applied for this field.

The class will define a `validate` method for performing generic validations like required check and length checks.

The class will have `to_python` abstract method that will need to be implemented by all inheriting classes.

The class will have `clean` method that will 

1. Covert the data to native type.
1. Run the validate method.
1. Run the validators defined during initialization.

## Usage
The abstract class will never be used directly and instead a subclass such as a `StringField` that inherits from the `Field` class will be used for defining the Entity fields. 

An example would be like:

```python
class StringField(Field):
    def to_python(self, value):
        if isinstance(value, str) or value is None:
            return value
        return str(value)

class School(Entity):
    name = StringField(required=True)
```

**Comment by subhashb** [comment]
- `max_length` may not be appropriate for definition in the base class. It is probably apt for a subset of text-related fields. `min_length` should be added too.
- Can we override __getattr__ method instead of `to_python`?
- Can we simply call the class `String` instead of `StringField`?
- Should we include an attribute for defining which attribute is the `primary_key` attribute?

**Comment by abhishek-ram** [comment]
- Yes i guess we can move those to the text related fields.
- We could but `to_python` is more explicit and we need to call it inside `clean` so a named function is better.
- Yes we can do that
- I am not sure if `primary_key` has a meaning at the Entity level...

**Comment by subhashb** [comment]
2. Aah, ok. Need to understand the intent behind `to_python.` Can you elaborate? The thing that I don't like about it is the method name doesn't tell what it is doing. Is it sanitizing, or is it returning the formatted value, or is it verifying data type, etc.? Once we understand, a better name might be obvious.
4. It is not exactly `primary_key.` It's more of an `id` field amongst attributes. I think later we will need such a field level identifier to automatically find which attribute to use to query upon in a repository. But I might be violating my recommendation of not engineering for the future. Let's not add it.

**Comment by abhishek-ram** [comment]
2. The `to_python` function here does the conversion of the value to native python type. We use this so that even if a string is passed to say a Boolean Field then its converted to python `bool`datatype.

**Comment by subhashb** [comment]
We will have strong data type validations in place, which will kick in well before this type of conversion becomes necessary. The entity layer will need to be "strongly typed" in nature, so we will avoid implicit type conversions or transfers. Let's hold onto this one for now and come back to it later if necessary?

**Comment by abhishek-ram** [comment]
2. So if this is the case then it does not make sense to have a `clean` function and instead we should just have a `validate` function.

**Comment by subhashb** [comment]
2. Yes, absolutely 👍
