### ISSUE TITLE
Ability to store dict as json in Postgres

### ISSUE THREAD

**Issue by advishnuprasad** [proteanhq/protean#328]
The dict field in protean stored as bytea in Postgres. Is it possible to store it as JSON?

**Comment by subhashb** [comment]
We can safely move to `sqlalchemy.types.JSON` for `Dict` data type, because JSON is supported by Postgresql, Mysql, and SQLite (the most commonly used databases. We should probably restrict this datatype to the 3 databases, but we can do that as a separate change.
