### ISSUE TITLE
Run Pylint checks as part of tests

### ISSUE THREAD

**Issue by subhashb** [proteanhq/protean#5]
`.pylintrc` is already part of the codebase. All python files, except maybe configuration files, should be linted, including test classes.

**Comment by abhishek-ram** [comment]
How about using this service https://www.codacy.com/product

**Comment by subhashb** [comment]
This looks good. Let's go ahead and use it. Will subscribe and confirm.

**Comment by subhashb** [comment]
I have added the project to Codacy: https://app.codacy.com/project/subhashb/protean/dashboard

Let's add a badge to the repo, and also address issues raised by Codacy. If we need to break the issues into different items, we can do that.

**Comment by subhashb** [comment]
I have added a separate ticket to remove Pylint as the primary linter. Two reasons:
1. Pylint has a lot of edge cases that are difficult to satisfy in a dynamic attribute framework like Protean (especially the `no-member` warning)
2. We should eventually implement a custom pylint-plugin that understands Protean structure and its attributes (like [Pylint-Django](https://github.com/PyCQA/pylint-django))
