### ISSUE TITLE
Enhancement to querying support 1 - Chaining filters

### ISSUE THREAD

**Issue by abhishek-ram** [proteanhq/protean#67]
The filter function should not execute and instead should return a cloned copy after persisting the passed filters. The query will only be executed when the `__iter__` is called on the resultant object. 
This will allow us to support the following:

```
Entry.filter(created_by=account).order_by('-created_at')
Entry.filter(votes__gte=10).exclude(created_by=account)
```

We can take a look at Django and Elasticsearch DSL to see how it can be implemented

**Comment by subhashb** [comment]
Resolved by https://github.com/proteanhq/protean/pull/69
