### ISSUE TITLE
Add Float Field Implementation

### ISSUE THREAD

**Issue by subhashb** [proteanhq/protean#8]
Validations: IsFloat, Maximum Length, Minimum Length
Typing: Convert Integer to Float automatically

Add test cases as usual.

**Comment by abhishek-ram** [comment]
why do we need IsFloat... are we not doing a type check already

**Comment by abhishek-ram** [comment]
Also what is the length here as we do not have length for floats

**Comment by subhashb** [comment]
Sorry, typo. Change to Maximum Value, Minimum Value.
If type checks are present and generic, we don't need a special method to check for float 👍
