### ISSUE TITLE
Add Boolean Field Implementation

### ISSUE THREAD

**Issue by subhashb** [proteanhq/protean#9]
Validations: IsBoolean value
Typing: Convert "True" and "False" to boolean values automatically

Add test cases as usual.

**Comment by abhishek-ram** [comment]
I thought we decided not to do type conversions, if we are going to do this then better to bring back the to_python function

**Comment by subhashb** [comment]
Agree, let's ignore type conversions for the initial version. We will discover if we need them.

**Comment by abhishek-ram** [comment]
actually @subhashb  thinking about it we can actually rename the `_validate_type` as `_cast_to_type` and introduce this functionality now.

**Comment by subhashb** [comment]
I am more interested in strict type validation than automatic conversion. That much I am certain. Let's implement this later if needed.
